server:
  port: 8082

spring:
  flyway:
    locations: classpath:db/migration/{vendor}
  rsocket:
    server:
      transport: websocket
      mapping-path: /rsocket
      port: 7002
  datasource:
    url: jdbc:h2:mem:order
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    open-in-view: true
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  application:
    name: order-demo

axon:
  metrics:
    micrometer:
      dimensional: true
  serializer:
    general: jackson
    messages: jackson
    events: jackson

order:
  snapshot-trigger-treshold-order: 200
management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"


